use std::{env, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct RuntimeModeProfilesFile {
    capabilities: RuntimeModeCapabilities,
    profiles: Vec<RuntimeModeProfile>,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeCapabilities {
    standby_drop_mv: U16Bounds,
    input_uvlo_threshold_mv: U16Bounds,
    input_uvlo_required_samples: U8Bounds,
    source_limited_enter_delta_ma: I16Bounds,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeProfile {
    id: String,
    max_rated_vout_mv: u16,
    defaults: RuntimeModeDefaults,
    fixed_policy: RuntimeModeFixedPolicy,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeDefaults {
    standby_drop_mv: u16,
    input_uvlo_cutoff_mv: u16,
    input_uvlo_recover_mv: u16,
    input_uvlo_required_samples: u8,
    source_limited_enter_delta_ma: i16,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeFixedPolicy {
    assist_low_drop_mv: u16,
    assist_enter_iout_ma: i32,
    assist_exit_iout_ma: i32,
    assist_required_samples: u8,
    assist_ramp_step_mv: u16,
    assist_ramp_interval_ms: u16,
    rated_enter_iout_ma: i32,
    rated_exit_iout_ma: i32,
    vin_drop_threshold_pct: u16,
    required_samples: u8,
    source_limited_vin_drop_pct: u16,
    source_limited_exit_iout_ma: i32,
    source_limited_required_samples: u8,
    source_limited_recover_margin_mv: u16,
}

#[derive(Debug, Deserialize)]
struct U16Bounds {
    min: u16,
    max: u16,
    step: u16,
}

#[derive(Debug, Deserialize)]
struct U8Bounds {
    min: u8,
    max: u8,
    step: u8,
}

#[derive(Debug, Deserialize)]
struct I16Bounds {
    min: i16,
    max: i16,
    step: i16,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let profiles_path = manifest_dir.join("../../schemas/runtime_mode_profiles.json");
    println!("cargo:rerun-if-changed={}", profiles_path.display());

    let source = fs::read_to_string(&profiles_path).expect("read runtime_mode_profiles.json");
    let profiles: RuntimeModeProfilesFile =
        serde_json::from_str(&source).expect("parse runtime_mode_profiles.json");

    let mut generated = String::new();
    generated.push_str(
        "// @generated by firmware/host-unit-tests/build.rs from schemas/runtime_mode_profiles.json\n",
    );
    generated.push_str("pub const ADVANCED_POWER_CAPABILITY_BOUNDS: AdvancedPowerCapabilityBounds = AdvancedPowerCapabilityBounds {\n");
    generated.push_str(&format!(
        "    standby_drop_mv: AdvancedPowerU16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.standby_drop_mv.min,
        profiles.capabilities.standby_drop_mv.max,
        profiles.capabilities.standby_drop_mv.step
    ));
    generated.push_str(&format!(
        "    input_uvlo_threshold_mv: AdvancedPowerU16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.input_uvlo_threshold_mv.min,
        profiles.capabilities.input_uvlo_threshold_mv.max,
        profiles.capabilities.input_uvlo_threshold_mv.step
    ));
    generated.push_str(&format!(
        "    input_uvlo_required_samples: AdvancedPowerU8CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.input_uvlo_required_samples.min,
        profiles.capabilities.input_uvlo_required_samples.max,
        profiles.capabilities.input_uvlo_required_samples.step
    ));
    generated.push_str(&format!(
        "    source_limited_enter_delta_ma: AdvancedPowerI16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.source_limited_enter_delta_ma.min,
        profiles.capabilities.source_limited_enter_delta_ma.max,
        profiles.capabilities.source_limited_enter_delta_ma.step
    ));
    generated.push_str("};\n\n");

    generated.push_str("pub const RUNTIME_MODE_PROFILES: [RuntimeModeProfileDefinition; ");
    generated.push_str(&profiles.profiles.len().to_string());
    generated.push_str("] = [\n");
    for profile in &profiles.profiles {
        generated.push_str("    RuntimeModeProfileDefinition {\n");
        generated.push_str(&format!("        id: \"{}\",\n", profile.id));
        generated.push_str(&format!(
            "        max_rated_vout_mv: {},\n",
            profile.max_rated_vout_mv
        ));
        generated.push_str("        defaults: AdvancedPowerSettingsSnapshot {\n");
        generated.push_str(&format!(
            "            standby_drop_mv: {},\n",
            profile.defaults.standby_drop_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_cutoff_mv: {},\n",
            profile.defaults.input_uvlo_cutoff_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_recover_mv: {},\n",
            profile.defaults.input_uvlo_recover_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_required_samples: {},\n",
            profile.defaults.input_uvlo_required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_enter_delta_ma: {},\n",
            profile.defaults.source_limited_enter_delta_ma
        ));
        generated.push_str("        },\n");
        generated.push_str("        fixed_policy: RuntimeModeFixedPolicy {\n");
        generated.push_str(&format!(
            "            assist_low_drop_mv: {},\n",
            profile.fixed_policy.assist_low_drop_mv
        ));
        generated.push_str(&format!(
            "            assist_enter_iout_ma: {},\n",
            profile.fixed_policy.assist_enter_iout_ma
        ));
        generated.push_str(&format!(
            "            assist_exit_iout_ma: {},\n",
            profile.fixed_policy.assist_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            assist_required_samples: {},\n",
            profile.fixed_policy.assist_required_samples
        ));
        generated.push_str(&format!(
            "            assist_ramp_step_mv: {},\n",
            profile.fixed_policy.assist_ramp_step_mv
        ));
        generated.push_str(&format!(
            "            assist_ramp_interval_ms: {},\n",
            profile.fixed_policy.assist_ramp_interval_ms
        ));
        generated.push_str(&format!(
            "            rated_enter_iout_ma: {},\n",
            profile.fixed_policy.rated_enter_iout_ma
        ));
        generated.push_str(&format!(
            "            rated_exit_iout_ma: {},\n",
            profile.fixed_policy.rated_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            vin_drop_threshold_pct: {},\n",
            profile.fixed_policy.vin_drop_threshold_pct
        ));
        generated.push_str(&format!(
            "            required_samples: {},\n",
            profile.fixed_policy.required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_vin_drop_pct: {},\n",
            profile.fixed_policy.source_limited_vin_drop_pct
        ));
        generated.push_str(&format!(
            "            source_limited_exit_iout_ma: {},\n",
            profile.fixed_policy.source_limited_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            source_limited_required_samples: {},\n",
            profile.fixed_policy.source_limited_required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_recover_margin_mv: {},\n",
            profile.fixed_policy.source_limited_recover_margin_mv
        ));
        generated.push_str("        },\n");
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(
        out_dir.join("runtime_mode_profiles_generated.rs"),
        generated,
    )
    .expect("write runtime_mode_profiles_generated.rs");
}
