#[path = "build_support/wifi_env.rs"]
mod wifi_env;

use std::{
    env, fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct RuntimeModeProfilesFile {
    capabilities: RuntimeModeCapabilities,
    profiles: Vec<RuntimeModeProfile>,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeCapabilities {
    standby_drop_mv: U16Bounds,
    input_uvlo_threshold_mv: U16Bounds,
    input_uvlo_required_samples: U8Bounds,
    source_limited_enter_delta_ma: I16Bounds,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeProfile {
    id: String,
    max_rated_vout_mv: u16,
    defaults: RuntimeModeDefaults,
    fixed_policy: RuntimeModeFixedPolicy,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeDefaults {
    standby_drop_mv: u16,
    input_uvlo_cutoff_mv: u16,
    input_uvlo_recover_mv: u16,
    input_uvlo_required_samples: u8,
    source_limited_enter_delta_ma: i16,
}

#[derive(Debug, Deserialize)]
struct RuntimeModeFixedPolicy {
    assist_low_drop_mv: u16,
    assist_enter_iout_ma: i32,
    assist_exit_iout_ma: i32,
    assist_required_samples: u8,
    assist_ramp_step_mv: u16,
    assist_ramp_interval_ms: u16,
    rated_enter_iout_ma: i32,
    rated_exit_iout_ma: i32,
    vin_drop_threshold_pct: u16,
    required_samples: u8,
    source_limited_vin_drop_pct: u16,
    source_limited_exit_iout_ma: i32,
    source_limited_required_samples: u8,
    source_limited_recover_margin_mv: u16,
}

#[derive(Debug, Deserialize)]
struct U16Bounds {
    min: u16,
    max: u16,
    step: u16,
}

#[derive(Debug, Deserialize)]
struct U8Bounds {
    min: u8,
    max: u8,
    step: u8,
}

#[derive(Debug, Deserialize)]
struct I16Bounds {
    min: i16,
    max: i16,
    step: i16,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let profile = env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string());
    println!("cargo:rustc-env=FW_BUILD_PROFILE={}", profile);

    emit_rerun_if_exists(&manifest_dir.join("build.rs"));
    emit_rerun_if_exists(&manifest_dir.join("Cargo.toml"));
    emit_rerun_for_dir(&manifest_dir.join("src"));

    if let Some(git_dir) = resolve_git_dir(&manifest_dir) {
        for rel in ["HEAD", "logs/HEAD", "packed-refs", "index"] {
            emit_rerun_if_exists(&git_dir.join(rel));
        }
    }

    let git_sha = git_rev_parse_short_head(&manifest_dir);
    println!("cargo:rustc-env=FW_GIT_SHA={}", git_sha);
    let src_hash_hex = format!("{:016x}", source_hash(&manifest_dir));
    println!("cargo:rustc-env=FW_SRC_HASH={}", src_hash_hex);
    let git_dirty = git_dirty_state(&manifest_dir);
    println!("cargo:rustc-env=FW_GIT_DIRTY={}", git_dirty);
    let build_features = enabled_features();
    for (env_key, _) in FEATURE_ENV_CANDIDATES {
        println!("cargo:rerun-if-env-changed={}", env_key);
    }
    println!("cargo:rustc-env=FW_FEATURES={}", build_features.join(","));
    println!(
        "cargo:rustc-env=FW_BUILD_ID={}-{}-{}",
        git_sha, git_dirty, src_hash_hex
    );

    let repo_root = manifest_dir.parent().map(Path::to_path_buf);
    if let Some(repo_root) = repo_root.as_deref() {
        for env_path in wifi_env::candidate_env_paths(repo_root) {
            emit_rerun_if_exists(&env_path);
        }
    }
    for key in wifi_env::WIFI_ENV_KEYS {
        println!("cargo:rerun-if-env-changed={}", key);
    }
    emit_wifi_env(repo_root.as_deref());

    let profiles_path = manifest_dir.join("../schemas/runtime_mode_profiles.json");
    println!("cargo:rerun-if-changed={}", profiles_path.display());

    let source = fs::read_to_string(&profiles_path).expect("read runtime_mode_profiles.json");
    let profiles: RuntimeModeProfilesFile =
        serde_json::from_str(&source).expect("parse runtime_mode_profiles.json");

    let mut generated = String::new();
    generated
        .push_str("// @generated by firmware/build.rs from schemas/runtime_mode_profiles.json\n");
    generated.push_str("pub const ADVANCED_POWER_CAPABILITY_BOUNDS: AdvancedPowerCapabilityBounds = AdvancedPowerCapabilityBounds {\n");
    generated.push_str(&format!(
        "    standby_drop_mv: AdvancedPowerU16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.standby_drop_mv.min,
        profiles.capabilities.standby_drop_mv.max,
        profiles.capabilities.standby_drop_mv.step
    ));
    generated.push_str(&format!(
        "    input_uvlo_threshold_mv: AdvancedPowerU16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.input_uvlo_threshold_mv.min,
        profiles.capabilities.input_uvlo_threshold_mv.max,
        profiles.capabilities.input_uvlo_threshold_mv.step
    ));
    generated.push_str(&format!(
        "    input_uvlo_required_samples: AdvancedPowerU8CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.input_uvlo_required_samples.min,
        profiles.capabilities.input_uvlo_required_samples.max,
        profiles.capabilities.input_uvlo_required_samples.step
    ));
    generated.push_str(&format!(
        "    source_limited_enter_delta_ma: AdvancedPowerI16CapabilityBounds {{ min: {}, max: {}, step: {} }},\n",
        profiles.capabilities.source_limited_enter_delta_ma.min,
        profiles.capabilities.source_limited_enter_delta_ma.max,
        profiles.capabilities.source_limited_enter_delta_ma.step
    ));
    generated.push_str("};\n\n");

    generated.push_str("pub const RUNTIME_MODE_PROFILES: [RuntimeModeProfileDefinition; ");
    generated.push_str(&profiles.profiles.len().to_string());
    generated.push_str("] = [\n");
    for profile in &profiles.profiles {
        generated.push_str("    RuntimeModeProfileDefinition {\n");
        generated.push_str(&format!("        id: \"{}\",\n", profile.id));
        generated.push_str(&format!(
            "        max_rated_vout_mv: {},\n",
            profile.max_rated_vout_mv
        ));
        generated.push_str("        defaults: AdvancedPowerSettingsSnapshot {\n");
        generated.push_str(&format!(
            "            standby_drop_mv: {},\n",
            profile.defaults.standby_drop_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_cutoff_mv: {},\n",
            profile.defaults.input_uvlo_cutoff_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_recover_mv: {},\n",
            profile.defaults.input_uvlo_recover_mv
        ));
        generated.push_str(&format!(
            "            input_uvlo_required_samples: {},\n",
            profile.defaults.input_uvlo_required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_enter_delta_ma: {},\n",
            profile.defaults.source_limited_enter_delta_ma
        ));
        generated.push_str("        },\n");
        generated.push_str("        fixed_policy: RuntimeModeFixedPolicy {\n");
        generated.push_str(&format!(
            "            assist_low_drop_mv: {},\n",
            profile.fixed_policy.assist_low_drop_mv
        ));
        generated.push_str(&format!(
            "            assist_enter_iout_ma: {},\n",
            profile.fixed_policy.assist_enter_iout_ma
        ));
        generated.push_str(&format!(
            "            assist_exit_iout_ma: {},\n",
            profile.fixed_policy.assist_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            assist_required_samples: {},\n",
            profile.fixed_policy.assist_required_samples
        ));
        generated.push_str(&format!(
            "            assist_ramp_step_mv: {},\n",
            profile.fixed_policy.assist_ramp_step_mv
        ));
        generated.push_str(&format!(
            "            assist_ramp_interval_ms: {},\n",
            profile.fixed_policy.assist_ramp_interval_ms
        ));
        generated.push_str(&format!(
            "            rated_enter_iout_ma: {},\n",
            profile.fixed_policy.rated_enter_iout_ma
        ));
        generated.push_str(&format!(
            "            rated_exit_iout_ma: {},\n",
            profile.fixed_policy.rated_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            vin_drop_threshold_pct: {},\n",
            profile.fixed_policy.vin_drop_threshold_pct
        ));
        generated.push_str(&format!(
            "            required_samples: {},\n",
            profile.fixed_policy.required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_vin_drop_pct: {},\n",
            profile.fixed_policy.source_limited_vin_drop_pct
        ));
        generated.push_str(&format!(
            "            source_limited_exit_iout_ma: {},\n",
            profile.fixed_policy.source_limited_exit_iout_ma
        ));
        generated.push_str(&format!(
            "            source_limited_required_samples: {},\n",
            profile.fixed_policy.source_limited_required_samples
        ));
        generated.push_str(&format!(
            "            source_limited_recover_margin_mv: {},\n",
            profile.fixed_policy.source_limited_recover_margin_mv
        ));
        generated.push_str("        },\n");
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(
        out_dir.join("runtime_mode_profiles_generated.rs"),
        generated,
    )
    .expect("write runtime_mode_profiles_generated.rs");

    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if arch == "xtensa" {
        println!("cargo:rustc-link-arg-bins=-Tlinkall.x");
        println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    }
}

fn enabled_features() -> Vec<&'static str> {
    FEATURE_ENV_CANDIDATES
        .iter()
        .filter_map(|(env_key, feature)| env::var_os(env_key).map(|_| *feature))
        .collect()
}

const FEATURE_ENV_CANDIDATES: &[(&str, &str)] = &[
    ("CARGO_FEATURE_NET_HTTP", "net_http"),
    ("CARGO_FEATURE_WEB_SERIAL", "web_serial"),
    ("CARGO_FEATURE_MAIN_VOUT_12V", "main-vout-12v"),
    ("CARGO_FEATURE_MAIN_VOUT_19V", "main-vout-19v"),
    ("CARGO_FEATURE_FORCE_MIN_CHARGE", "force-min-charge"),
    ("CARGO_FEATURE_BMS_DUAL_PROBE_DIAG", "bms-dual-probe-diag"),
    ("CARGO_FEATURE_TMP_HW_PROTECT_TEST", "tmp-hw-protect-test"),
    ("CARGO_FEATURE_TEST_FW", "test-fw"),
    ("CARGO_FEATURE_TPS_TEST_FW", "tps-test-fw"),
    ("CARGO_FEATURE_TPS_TEST_OUT_A", "tps-test-out-a"),
    ("CARGO_FEATURE_TPS_TEST_OUT_B", "tps-test-out-b"),
    ("CARGO_FEATURE_TPS_TEST_OUT_BOTH", "tps-test-out-both"),
    ("CARGO_FEATURE_TPS_TEST_FPWM", "tps-test-fpwm"),
    ("CARGO_FEATURE_TPS_TEST_PFM", "tps-test-pfm"),
    ("CARGO_FEATURE_TPS_TEST_VOUT_5V", "tps-test-vout-5v"),
    ("CARGO_FEATURE_TPS_TEST_VOUT_12V", "tps-test-vout-12v"),
    ("CARGO_FEATURE_TPS_TEST_VOUT_15V", "tps-test-vout-15v"),
    ("CARGO_FEATURE_TPS_TEST_VOUT_19V", "tps-test-vout-19v"),
    ("CARGO_FEATURE_TPS_TEST_ILIM_1P5A", "tps-test-ilim-1p5a"),
    ("CARGO_FEATURE_TPS_TEST_ILIM_3P5A", "tps-test-ilim-3p5a"),
    ("CARGO_FEATURE_TPS_TEST_CHARGE_OFF", "tps-test-charge-off"),
    ("CARGO_FEATURE_TPS_TEST_CHARGE_MIN", "tps-test-charge-min"),
    ("CARGO_FEATURE_TPS_TEST_CHARGE_1A", "tps-test-charge-1a"),
    (
        "CARGO_FEATURE_TEST_FW_SCREEN_STATIC",
        "test-fw-screen-static",
    ),
    (
        "CARGO_FEATURE_TEST_FW_AUDIO_PLAYBACK",
        "test-fw-audio-playback",
    ),
    (
        "CARGO_FEATURE_TEST_FW_DEFAULT_SCREEN_STATIC",
        "test-fw-default-screen-static",
    ),
    (
        "CARGO_FEATURE_TEST_FW_DEFAULT_AUDIO_PLAYBACK",
        "test-fw-default-audio-playback",
    ),
    ("CARGO_FEATURE_DISPLAY_SPI_20MHZ", "display-spi-20mhz"),
    ("CARGO_FEATURE_DISPLAY_SPI_40MHZ", "display-spi-40mhz"),
    ("CARGO_FEATURE_NO_PD_SINK_5V", "no-pd-sink-5v"),
    ("CARGO_FEATURE_NO_PD_SINK_9V", "no-pd-sink-9v"),
    ("CARGO_FEATURE_NO_PD_SINK_12V", "no-pd-sink-12v"),
    ("CARGO_FEATURE_NO_PD_SINK_15V", "no-pd-sink-15v"),
    ("CARGO_FEATURE_NO_PD_SINK_20V", "no-pd-sink-20v"),
    ("CARGO_FEATURE_NO_PPS", "no-pps"),
];

fn emit_rerun_if_exists(path: &Path) {
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn emit_rerun_for_dir(dir: &Path) {
    let mut files = Vec::new();
    collect_files(dir, &mut files);
    files.sort();
    for path in files {
        emit_rerun_if_exists(&path);
    }
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    if !dir.is_dir() {
        return;
    }
    let entries = match fs::read_dir(dir) {
        Ok(v) => v,
        Err(_) => return,
    };
    let mut paths = entries
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .collect::<Vec<_>>();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            collect_files(&path, out);
        } else if path.is_file() {
            out.push(path);
        }
    }
}

fn resolve_git_dir(manifest_dir: &Path) -> Option<PathBuf> {
    let output = std::process::Command::new("git")
        .current_dir(manifest_dir)
        .args(["rev-parse", "--git-dir"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let git_dir = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if git_dir.is_empty() {
        return None;
    }
    let path = PathBuf::from(git_dir);
    Some(if path.is_absolute() {
        path
    } else {
        manifest_dir.join(path)
    })
}

fn git_rev_parse_short_head(manifest_dir: &Path) -> String {
    std::process::Command::new("git")
        .current_dir(manifest_dir)
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
            } else {
                None
            }
        })
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_string())
}

fn source_hash(manifest_dir: &Path) -> u64 {
    let mut files = Vec::new();
    let cargo_toml = manifest_dir.join("Cargo.toml");
    let build_rs = manifest_dir.join("build.rs");
    if cargo_toml.is_file() {
        files.push(cargo_toml);
    }
    if build_rs.is_file() {
        files.push(build_rs);
    }
    collect_files(&manifest_dir.join("src"), &mut files);
    files.sort();

    let mut hash = 0xcbf29ce484222325u64;
    for path in files {
        let rel = path.strip_prefix(manifest_dir).unwrap_or(&path);
        hash_bytes(&mut hash, rel.to_string_lossy().as_bytes());
        hash_bytes(&mut hash, &[0]);
        if let Ok(content) = fs::read(&path) {
            hash_bytes(&mut hash, &content);
        }
        hash_bytes(&mut hash, &[0xff]);
    }
    hash
}

fn hash_bytes(hash: &mut u64, bytes: &[u8]) {
    for byte in bytes {
        *hash ^= *byte as u64;
        *hash = hash.wrapping_mul(0x100000001b3);
    }
}

fn git_dirty_state(manifest_dir: &Path) -> &'static str {
    let output = std::process::Command::new("git")
        .current_dir(manifest_dir)
        .args([
            "status",
            "--porcelain",
            "--untracked-files=no",
            "--",
            "src",
            "Cargo.toml",
            "build.rs",
        ])
        .output();
    match output {
        Ok(out) if out.status.success() => {
            if String::from_utf8_lossy(&out.stdout).trim().is_empty() {
                "clean"
            } else {
                "dirty"
            }
        }
        _ => "unknown",
    }
}

fn emit_wifi_env(repo_root: Option<&Path>) {
    let cfg = wifi_env::WifiEnvConfig::from_sources(repo_root);
    for key in wifi_env::WIFI_ENV_KEYS {
        if let Some(value) = cfg.get(key) {
            println!("cargo:rustc-env={}={}", key, value);
        }
    }
}
